trigger:
- '*'

pr: 
- '*'

pool: Default

resources:
  repositories:
    - repository: Template
      type: github
      endpoint: gunnargestsson # Service Connection
      name: gunnargestsson/bcbuildtemplate
      ref: master

variables:
- group: BuildVariables

extends:
  template: /.azureDevOps/CI.yml@Template
  parameters:
    version: "current"
    appVersion: "19.0"
    azureSubscription: "Microsoft Partner Network"    
