trigger:
- master

variables:
- group: BuildVariables
- group: InsiderBuilds

pool: 
  vmImage: windows-latest

resources:
  repositories:
    - repository: Template
      type: github
      endpoint: gunnargestsson # Service Connection
      name: gunnargestsson/bcbuildtemplate
      ref: master

extends:
  template: /.azureDevOps/CI.yml@Template
  parameters:
    version: "nextminor"
    appVersion: "19.0"
    azureSubscription: "Microsoft Partner Network"   
